version: '2'
services:
  app:
    build: .
    links:
      - mysql
      - redis
    volumes:
      - ./:/var/www/html
      - ./data/certs:/etc/ssl/apache2
      - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - '443:443'
    env_file: .env

  # The Database
  mysql:
    image: mysql:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'
