version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: ./dockerfiles/app.Dockerfile
    links:
      - mysql
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file: .env

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: ./dockerfiles/web.Dockerfile
    links:
      - mysql
    working_dir: /var/www
    volumes:
      - ./data/certs:/etc/nginx/ssl
    volumes_from:
      - app
    ports:
      - 443:443
    env_file: .env

  # The Database
  mysql:
    image: mysql:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'
volumes:
  dbdata:
